import type { Entity } from "../General"
import type { EntityTarget, InstancesOf } from "../General"
import type { RelationHandler } from "../../Relations"

type PropertyMetadata = { __property?: true }
type AutoGeneratedPropertyMetadata = { __autoGenerated?: true }
type ForeignKeyMetadata = { __foreignKey?: true }
type TypeKeyMetadata = { __typeKey?: true }

export type Prop<T = any> = T & PropertyMetadata
export type AutoGenProp<T = any> = (
    Prop<T> & AutoGeneratedPropertyMetadata
)
export type FKProp<T = any> = (
    Prop<T> & ForeignKeyMetadata
)
export type TKProp<T extends string | EntityTarget[] = string> = (
    Prop<
        T extends string
        ? T
        : T extends EntityTarget[]
        ? InstancesOf<T>[number]['__name']
        : never
    > & TypeKeyMetadata
)

// ----------------------------------------------------------------------------

export type EntityPropertiesKeys<T extends Entity> = {
    [K in keyof T]: (
        T[K] extends PropertyMetadata
        ? Extract<K, string>
        : never
    )
}[keyof T]

export type EntityProperties<T extends Entity> = Pick<
    T,
    EntityPropertiesKeys<T>
>

// ----------------------------------------------------------------------------

export type EntityRelationsKeys<T extends Entity> = {
    [K in keyof T]: (
        T[K] extends null
        ? never
        : T[K] extends RelationHandler
        ? Extract<K, string>
        : never
    )
}[keyof T]

export type EntityRelations<T extends Entity> = Pick<
    T,
    EntityRelationsKeys<T>
>

// ----------------------------------------------------------------------------

export type ExcludeRelationAttributesKeys<T extends any> = {
    [K in keyof T]: T[K] extends ForeignKeyMetadata | TypeKeyMetadata
    ? never
    : K
}[keyof T]

export type ExcludeRelationAttributes<T extends any> = Pick<
    T, ExcludeRelationAttributesKeys<T>
>

// ----------------------------------------------------------------------------

export type OptionalNullable<T> = (
    {
        [K in keyof T as (
            T[K] extends AutoGeneratedPropertyMetadata
            ? K
            : undefined extends T[K]
            ? K
            : null extends T[K]
            ? K
            : never

        )]?: T[K]
    } & {
        [K in keyof T as (
            T[K] extends AutoGeneratedPropertyMetadata
            ? never
            : undefined extends T[K] ? never
            : null extends T[K] ? never
            : K
        )]: T[K]
    }
)