import type { Entity } from "../General"

type PropertyMetadata = { __property?: true }
type AutoGeneratedPropertyMetadata = { __autoGenerated?: true }
type ForeignKeyMetadata = { __foreignKey?: true }
type TypeKeyMetadata = { __typeKey?: true }

export type Property<T> = T & PropertyMetadata
export type AutoGeneratedProperty<T> = (
    Property<T> & AutoGeneratedPropertyMetadata
)
export type ForeignKeyProperty<T> = (
    Property<T> & ForeignKeyMetadata
)
export type TypeKeyProperty<T> = (
    Property<T> & TypeKeyMetadata
)

// ----------------------------------------------------------------------------

export type EntityPropertiesKeys<T extends Entity> = {
    [K in keyof T]: (
        T[K] extends PropertyMetadata
        ? Extract<K, string>
        : never
    )
}[keyof T]

export type EntityProperties<T extends Entity> = Pick<
    T,
    EntityPropertiesKeys<T>
>

// ----------------------------------------------------------------------------

export type EntityRelationsKeys<T extends Entity> = {
    [K in keyof T]: (
        T[K] extends null
        ? never
        : T[K] extends Entity | Entity[] | null
        ? K
        : never
    )
}[keyof T]

export type EntityRelations<T extends Entity> = Pick<
    T,
    EntityRelationsKeys<T>
>

// ----------------------------------------------------------------------------

export type ExcludeRelationAttributesKeys<T extends any> = {
    [K in keyof T]: T[K] extends ForeignKeyMetadata | TypeKeyMetadata
    ? never
    : K
}[keyof T]

export type ExcludeRelationAttributes<T extends any> = Pick<
    T, ExcludeRelationAttributesKeys<T>
>

// ----------------------------------------------------------------------------

export type OptionalNullable<T> = (
    {
        [K in keyof T as (
            T[K] extends AutoGeneratedPropertyMetadata
            ? K
            : undefined extends T[K]
            ? K
            : null extends T[K]
            ? K
            : never

        )]?: T[K]
    } & {
        [K in keyof T as (
            T[K] extends AutoGeneratedPropertyMetadata
            ? never
            : undefined extends T[K] ? never
            : null extends T[K] ? never
            : K
        )]: T[K]
    }
)