import type {
    Entity,
    Constructor,
    ConstructorsOf,
    InstancesOf,
    Primitive,

    Target,
    StaticTarget,
    EntityObject,
    EntityJSON,

    EntityTarget,
    StaticEntityTarget,

    PolymorphicEntityTarget,
    StaticPolymorphicEntityTarget,

    TargetMetadata,
    TargetRepository,
    TargetQueryBuilder,
    InternalPolymorphicEntityTarget,
    LocalOrInternalPolymorphicEntityTarget,

    AsEntityTarget,
    AsPolymorphicEntityTarget,

    CollectionTarget
} from "./General"

import type {
    Property,
    AutoGeneratedProperty,
    EntityProperties,
    EntityPropertiesKeys,
    EntityRelations,
    EntityRelationsKeys,
    OptionalNullable
} from "./Properties"

export type {
    Entity,
    Constructor,
    ConstructorsOf,
    InstancesOf,
    Primitive,

    Target,
    StaticTarget,
    EntityObject,
    EntityJSON,

    EntityTarget,
    StaticEntityTarget,

    PolymorphicEntityTarget,
    StaticPolymorphicEntityTarget,

    TargetMetadata,
    TargetRepository,
    TargetQueryBuilder,
    InternalPolymorphicEntityTarget,
    LocalOrInternalPolymorphicEntityTarget,

    AsEntityTarget,
    AsPolymorphicEntityTarget,

    CollectionTarget,

    Property,
    AutoGeneratedProperty,
    EntityProperties,
    EntityPropertiesKeys,
    EntityRelations,
    EntityRelationsKeys,
    OptionalNullable
}
